name: Run SCA scan with Snyk
on: push
jobs:
  Snykscan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build the code
      run: |
       echo "JAVA_HOME=$JAVA_HOME"
       mvn clean install -DskipTests
    - name: Run Snyk scan 
      uses: snyk/actions/maven@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
       args: test
